"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText, RefreshCw, Download, AlertCircle } from "lucide-react";
import { getNarrative, generateNarrative, type NarrativeReport } from "@/lib/api/fdd-client";
import { formatDateTime } from "@/lib/utils/format";

interface Props {
  dealId: string | null | undefined;
  deal: string;
}

function exportToPrintablePdf(report: NarrativeReport, deal: string) {
  const win = window.open("", "_blank", "width=900,height=1000");
  if (!win) return;

  const sectionsHtml = report.sections
    .map((s) => `<h2>${s.title}</h2><p>${s.content.replace(/\n/g, "<br/>")}</p>`)
    .join("\n");

  const html = `<!doctype html>
    <html>
      <head>
        <title>${deal} — Junior Analyst Report</title>
        <style>
          body { font-family: Georgia, 'Times New Roman', serif; max-width: 780px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
          h1 { font-size: 22px; border-bottom: 2px solid #1a1a1a; padding-bottom: 8px; }
          h2 { font-size: 16px; margin-top: 28px; color: #333; }
          p { font-size: 13px; }
          .meta { font-size: 11px; color: #666; margin-bottom: 24px; }
          .disclaimer { margin-top: 40px; font-size: 10px; color: #888; border-top: 1px solid #ccc; padding-top: 12px; }
        </style>
      </head>
      <body>
        <h1>${deal} — Junior Analyst Summary Report</h1>
        <p class="meta">Generated ${formatDateTime(report.generated_at)} — AI draft, requires analyst review</p>
        ${sectionsHtml}
        <p class="disclaimer">Auto-generated by the TAM Narrative Drafter from computed financial/QoE/red flag/NWC/net debt figures. Every figure quoted traces to a source report — see figures_used in the API response.</p>
      </body>
    </html>`;

  win.document.open();
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

export function JuniorAnalystReport({ dealId, deal }: Props) {
  const [report, setReport] = useState<NarrativeReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [regenerating, setRegenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!dealId) {
      setLoading(false);
      return;
    }
    setLoading(true);
    setError(null);
    getNarrative(dealId)
      .then(setReport)
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false));
  }, [dealId]);

  const handleRegenerate = async () => {
    if (!dealId) return;
    setRegenerating(true);
    setError(null);
    try {
      const result = await generateNarrative(dealId);
      setReport(result);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setRegenerating(false);
    }
  };

  if (!dealId) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center justify-center gap-2 py-10 text-center">
          <FileText className="h-8 w-8 text-muted-foreground/50" />
          <p className="text-sm font-medium text-muted-foreground">Junior Analyst Summary Report</p>
          <p className="text-xs text-muted-foreground">Upload and process a deal to generate the analyst report.</p>
        </CardContent>
      </Card>
    );
  }

  if (loading) {
    return (
      <Card>
        <CardContent className="space-y-3 py-6">
          <Skeleton className="h-6 w-1/2" />
          <Skeleton className="h-32 w-full" />
        </CardContent>
      </Card>
    );
  }

  if (error && !report) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center gap-3 py-8 text-center text-sm text-muted-foreground">
          <AlertCircle className="h-5 w-5" />
          <span>{error}</span>
          <Button size="sm" variant="outline" onClick={handleRegenerate} disabled={regenerating}>
            <RefreshCw className={`mr-1 h-3.5 w-3.5 ${regenerating ? "animate-spin" : ""}`} />
            {regenerating ? "Generating…" : "Generate Report"}
          </Button>
        </CardContent>
      </Card>
    );
  }

  if (!report || report.sections.length === 0) {
    return (
      <Card className="border-dashed">
        <CardContent className="flex flex-col items-center gap-3 py-8 text-center text-sm text-muted-foreground">
          <span>{report?.message ?? "No narrative generated yet."}</span>
          <Button size="sm" variant="outline" onClick={handleRegenerate} disabled={regenerating}>
            <RefreshCw className={`mr-1 h-3.5 w-3.5 ${regenerating ? "animate-spin" : ""}`} />
            {regenerating ? "Generating…" : "Generate Report"}
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-cyan-500" />
              Junior Analyst Summary Report
            </CardTitle>
            <p className="mt-1 text-xs text-muted-foreground">
              {deal} &nbsp;·&nbsp; Generated {formatDateTime(report.generated_at)} &nbsp;·&nbsp;{" "}
              <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-semibold text-amber-700 dark:bg-amber-900/40 dark:text-amber-400">
                AI Draft — Requires Analyst Review
              </span>
              {report.status === "partial" && (
                <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[11px] font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">
                  Some inputs unavailable: {report.data_gaps.join(", ")}
                </span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline" onClick={handleRegenerate} disabled={regenerating}>
              <RefreshCw className={`mr-1 h-3.5 w-3.5 ${regenerating ? "animate-spin" : ""}`} />
              {regenerating ? "Regenerating…" : "Regenerate"}
            </Button>
            <Button size="sm" variant="outline" onClick={() => exportToPrintablePdf(report, deal)}>
              <Download className="mr-1 h-3.5 w-3.5" />
              Export PDF
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4 md:grid-cols-2">
          {report.sections.map((section) => (
            <div key={section.section_id} className="rounded-lg border bg-muted/30 p-4">
              <h3 className="mb-2 text-sm font-semibold">{section.title}</h3>
              <p className="text-sm leading-relaxed text-muted-foreground whitespace-pre-line">{section.content}</p>
            </div>
          ))}
        </div>
        <p className="mt-4 text-[11px] text-muted-foreground/60">
          Drafted by the TAM Narrative Agent from computed financial/QoE/red flag/NWC/net debt figures only —
          every number above traces to a source report, never invented by the LLM. Requires senior analyst review before sign-off.
        </p>
      </CardContent>
    </Card>
  );
}
